# Generated by Django 5.1 on 2024-08-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_interest_users_interest_from_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='name',
        ),
        migrations.AddField(
            model_name='interest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
